# FUNCTION: a function is a reusable block of code that performs a specific task.
# it is defined using the def keyword and can be called whenever needed, which helps avoid writing the same code multiple times.


# Advantage
# it reduces duplocation and rewrite the same code at multiple times.
# we can solve error inside the function easily

# ####################### types ########################

# #####1 inbuild fuction: it can be already defined in python libtaty that type of function is know n as inbuilt function.
# example print(), len(), pop()



# #####2. user difined function##############
# syntax:
# def function_name():  #create function (parameter)

#     print("Hello world")      #body
# function_name()               #agrument

# example 2 : passing parameter and arguments.


# def rectangle(l , b):
#     print((l*b))
# rectangle(5,6)

############# 3. lambda function###############
############## 4. recursive function################


# #################QUESTION###############

# 1. Write a function to find the cube of a number.
# def cube (a):
#     print(a*a*a)
# cube(4)

# 2. Write a function to check whether a number is even or odd.
# def even_odd (num):
#     if num / 2 == 0:
#         print(num, "even number")
#     else:
#         print(num , "odd number")
# even_odd(5)

# 3. Write a function to find the largest of two numbers.
# def largest (num1,num2):
#     if num1>num2:
#         print(num1 ,  "num1 is largest")
#     else:
#         print(num2 , "num2 is largest")
# largest(2,3)

# 4. Write a function to deposit money into a bank account.

# def deposit_money (balance, account ):
#     print("deposit=", balance + account)
# deposit_money(1000,12)


# 5. Write a function to withdrawn money into a bank account. 
# def withdrawn(balance,account):
#     print("withdrawn",balance-account)
# withdrawn(1000,100)

# 6. if the per unit price of electricity bill is 12 then calculate the total price of 56 unit.
# def electricity_bill(perunit,):
#     print("bill=",perunit*12)
# electricity_bill(56)


# 7. Write a Python program using three user-defined functions to:
#     Deposit money

# def deposit(balance):
#     amount = float(input("enter the amount"))
#     print(balance+amount)
# deposit(1000)


#     Withdraw money
# def withdrawn(balance):
#     amount = float(input("=enter the amount"))
#     print(balance-amount)
# withdrawn(1000)

#     Display the current balance

# def current_balance(show):
#     print("the current amount is: ",show)
# current_balance(5000000000)




# def function_name():

#     print("Hello world")
# function_name()

# def car():
#     print("Hi I am car")
#     function_name()
# car()

# def add(a, b):      #parameter
#     print(a+b)

# add(2,3)            #agrument

# def rectangle(l , b):
#     print((l*b))
# rectangle(5,6)

# def area_of_circle(r):
#     print(3.14*r*r)
# area_of_circle(4)

# def kinetic_energy(m,v):
#     ke= 1/2*(m*v*v)
#     print(ke)
# kinetic_energy(100,3) 





